config/routes.rb
Rails.application.routes.draw do
  root to: "artists#index"

  devise_for :users
  resources :artists
  resources :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy

  validates :name, presence: true

  validates :bio, length: { maximum: 600 }

  has_many :photos, dependent: :destroy
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :artist
  

 mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  validates :title, presence: true
  validates :artist, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

def index
  @artists = Artist.all
end

def show
  @song = Song.new
  @photos = @artist.photos
end

def destroy
  @artist.destroy
  redirect_to root_path, notice: "Artist removed!"
end

private

def set_artist
  @artist = Artist.find(params[:id])
end

def artist_params
  params.require(:artist).permit(:first_name, :last_name, :bio)
end

def image_params
  params[:images].present? ? params.require(:images) : []
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :destroy]


#GET /songs
#GET /songs.json

  def index
    @songs = Song.all
  end

  def show
      @song = Song.find(params[:id])
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html{ redirect_to @song.artist, notice: "Song created"}
        format.json { render :show, status: :created, location: @song}
      else
        format.html {redirect_to @song.artist}
        format.json {render json: @song.errors, status: unprocessable_entity}
      end
    end
  end


  def destroy
      @song.destroy
      respond_to do |format|
        format.html { redirect_to @song.artist, notice: "Song deleted." }
        format.json { head :no_content }
      end
    end

  private

  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:title, :artist_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/index.html.erb
<style>

body {
  text-align: center;
  padding: 20px;
  background-color: 	#D0D0D0;


}

a{
  color: white;
}
.thumbnail {
  background-color: 	#888888;
}</style>

<div class="row">
  <div class="jumbotron">
    <h1>
  <span class="glyphicon glyphicon-music" aria-hidden="true"></span>
 Codaisseurify <span class="glyphicon glyphicon-music" aria-hidden="true"></span></h1>

</div>
  <% @artists.each do |artist| %>
    <div class="col-lg-6 col-sm-6">
      <div class="thumbnail">
        <% artist.photos.each do |photo| %>
          <%= image_tag photo.image %>
        <% end %>
        <div class="caption">
          <h4><%= link_to artist.name, artist  %></h4>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/artists/show.html.erb
<style>
body {
  text-align: center;

    padding: 20px;
    background-color: 	#D0D0D0;



}
 .row-1, .row-2, .row-3,.row-4 {
   padding-top: 10%;
 }


 .thumbnail {
   background-color: 	#888888;}


   }
.title {
  font-size: 35px;
}
</style>

<div class="container">
  <div class="row">
    <div class="jumbotron">
      <h1>
    <span class="glyphicon glyphicon-music" aria-hidden="true"></span>
   <%= @artist.name %> <span class="glyphicon glyphicon-music" aria-hidden="true"></span></h1>

  </div>

</div>
  </div>

  <div class="row-1">
    <div class="col-lg-6 col-sm-6">
       <% @artist.photos.each do |photo| %>
      <%= image_tag photo.image %>
      <%end%>

</div>
</div>

<div class="col-lg-6 col-sm-6">
<div class="row-2">

    <h3><b>Name</b>: <%= @artist.name %></h3>
    <h4><i><%= @artist.bio %></i></h4>

  </div>
  <div class="row-3"
  <h2><b>Songs</b></h2>
       <% if @artist.songs.any? %>

           <% @artist.songs.each do |song| %>
             <p class="title"><%= song.title %> </p>
             <p><%= link_to "Remove song", song_path(song.id), method: :delete, data: { confirm: "By pressing Ok you will be deleting this song. Are you sure you would like to continue?" } %></p>
           <% end %>

       <% else %>
         <p>This artist has no songs.</p>
       <% end %>
     </div>
</div>

</div>


<div class="row-4">
<p><%= link_to "Add a song", new_song_path%></p>

<p><%= link_to "Delete Artist", artist_path(@artist.id), method: :delete, data: { confirm: "Are you sure?" } %></p>
<p><%= link_to "Back", artists_path%></p>
</div>

app/views/home/index.html.erb
<div class="row">
  <p> <%= link_to "+ CREATE NEW ARTIST", new_artist_path, class: "btn btn-info" %> </p>
  <% @artists.each do |artist| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <% artist.photos.each do |photo| %>
          <%= image_tag photo.image.thumbnail %>
        <% end %>
        <div class="caption">
          <h3><%= link_to artist.first_name, artist %></h3>
          <h4><%= link_to artist.last_name, artist %> </h4>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
   <%= javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.min.js' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "shared/navbar" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Codaisseurify", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>

            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/songs/_form.html.erb
<%= form_for Song.new do |f| %>

<% if @song != nil %>
  <% @song.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

<% if @artist != nil %>
  <% @artist.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

<div>
    <label for="title">Song Title</label>
  <p>  <%= f.text_field :title, placeholder: "Song Title", class: "form-control" %></p>
</div>

<div>
    <label for="artist">Artist</label>
    <%= f.label :artist_id %>
    <%= f.collection_select(:artist_id, Artist.all, :id, :name) %>
  </div>

  <div class="actions">
    <%= f.submit "Create song", class: "btn btn-info" %>
  </div>
<% end %>

app/views/songs/_song.html.erb
<li class="song" data-id="<%= song.id %>">
  <input name="song[<%= song.id %>]" id="song-<%= song.id %>" type="checkbox" value="1">
  <label for="song-<%= song.id %>"><%= song.title %></label>
</li>

app/views/songs/new.html.erb
<style> body {
  text-align: center;
  padding: 20px;
  background-color: 	#D0D0D0;


}</style>

<div class="jumbotron">
  <h1>
<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
New song </span></h1>

</div>

<h2>Add a new song </h2>
    <%= render "form", song: @song %>